/* cxx_demangle_stubs.cpp
 * OCaml C stub for C++ symbol demangling via __cxa_demangle.
 *
 * Background: magic-trace reads ELF symbol tables via owee and passes symbol
 * names directly to the flamegraph renderer without any C++ demangling.
 * C++ symbols generated by modern compilers — especially deeply nested
 * std::variant / std::tuple instantiations, NTTPs, and C++20 template lambdas —
 * produce mangled names several hundred characters long
 * (e.g. _ZN5DepthILi3EE5InnerE...).  These appear verbatim in every magic-trace
 * flamegraph, making C++ traces effectively unreadable.
 *
 * __cxa_demangle, when called with (buf=NULL, n=NULL), malloc-allocates a
 * buffer exactly large enough for the demangled name.  Passing a fixed-size
 * stack buffer is unsafe: the demangler may realloc the buffer if it is too
 * small, and realloc'ing stack memory is undefined behaviour.  The NULL/NULL
 * calling convention is therefore the only safe one for callers that do not
 * already own a heap-allocated buffer.
 */

#include <stdlib.h>
#include <cxxabi.h>

#include <caml/mlvalues.h>
#include <caml/alloc.h>
#include <caml/memory.h>

extern "C" CAMLprim value magic_trace_cxx_demangle(value mangled_v)
{
  CAMLparam1(mangled_v);
  CAMLlocal1(str);

  int status = 0;
  /* See file header for why a heap-allocated buffer is the only safe choice. */
  char *demangled = abi::__cxa_demangle(String_val(mangled_v), NULL, NULL, &status);

  if (status != 0 || demangled == NULL) {
    /* status -1 = malloc failure, -2 = not a valid mangled name, -3 = bad arg.
     * The library returns NULL on every documented failure code; the free
     * below is belt-and-suspenders against any future ABI change. */
    if (demangled != NULL) free(demangled);
    CAMLreturn(Val_none);
  }

  str = caml_copy_string(demangled);
  free(demangled);
  CAMLreturn(caml_alloc_some(str));
}
