/* cxx_demangle_stubs.c
 * OCaml C stub for C++ symbol demangling via __cxa_demangle (libiberty / libstdc++).
 *
 * Background: magic-trace reads ELF symbol tables via owee and passes symbol names
 * directly to the flamegraph renderer without any C++ demangling.  C++ symbols
 * generated by modern compilers — especially deeply nested std::variant / std::tuple
 * instantiations, NTTPs, and C++20 template lambdas — produce mangled names several
 * hundred characters long (e.g. _ZN5DepthILi3EE5InnerE...).  These appear verbatim
 * in every magic-trace flamegraph, making C++ traces effectively unreadable.
 *
 * __cxa_demangle, when called with (buf=NULL, n=NULL), malloc-allocates a buffer
 * exactly large enough for the demangled name — there is no truncation regardless
 * of symbol length.  This is the correct calling convention; passing a pre-sized
 * stack buffer silently truncates long names.
 */

#include <stdlib.h>
#include <string.h>
#include <cxxabi.h>

#include <caml/mlvalues.h>
#include <caml/alloc.h>
#include <caml/memory.h>

extern "C" CAMLprim value magic_trace_cxx_demangle(value mangled_v)
{
  CAMLparam1(mangled_v);
  CAMLlocal1(str);

  int status = 0;
  /* Pass NULL buffer and NULL length so __cxa_demangle malloc-allocates the
   * exact size needed.  This is safe for arbitrarily long C++20 symbol names. */
  char *demangled = __cxxabiv1::__cxa_demangle(String_val(mangled_v), NULL, NULL, &status);

  if (status != 0 || demangled == NULL) {
    /* status -1 = malloc failure, -2 = not a valid mangled name, -3 = bad arg.
     * In all failure cases return None so the caller can fall back to the raw name. */
    if (demangled != NULL) free(demangled);
    CAMLreturn(Val_none);
  }

  str = caml_copy_string(demangled);
  free(demangled);
  CAMLreturn(caml_alloc_some(str));
}
