name: build-deb

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt install opam dune debhelper devscripts

      - name: Build packages
        run: |
          DEBFULLNAME="Jane Street" DEBEMAIL=opensource-contacts@janestreet.com dch -b --newversion "$(git describe --tags | sed 's/^v//')+deb$(grep VERSION_ID /etc/os-release | cut -d'"' -f2)" -D unstable 'Building latest upstream'
          dpkg-buildpackage -us -uc -b -j$(nproc)
          # Because actions/upload-artifact will refuse to upload relative paths...
          mv ../*.deb .

      - uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: '*.deb'
          if-no-files-found: error

      - name: Upload to GitHub releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.deb'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
